baseURL: https://scolohub.com/
languageCode: de-de
title: ScoloHub
theme: 
  - hugo-book
  - hugo-shortcode-gallery

services:
  googleAnalytics:
    ID: G-RSSEVRT14Z

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false