@startmindmap
* Scolopendromorpha

** ocelli absent
*** 23 Leg Bearing Segments
**** family Scolopocryptopidae
***** Prefemur of ultimate legs with 1 or 2 spinous processes.
****** subfamily Scolopocryptopinae
******* genus Scolopocryptops

***** Prefemur of ultimate legs with 3–6 spinous processes or 3–7 saw teeth, very rarely without projections.
****** Ultimate legs cryptopiform, their tibia and tarsus 1 with characteristic saw teeth.
******* subfamily Kethopinae
******** Sternites distinctly margined laterally, with both median and transverse sutures.
********* genus Kethops
******** Sternites without lateral margination, without median and transverse sutures.
********* genus Thalkethops
****** Ultimate legs elongated, their tibia and tarsus 1 lacking saw teeth, their tarsus 2 considerably transformed, i.e. consisting of numerous secondary articles or absent (rarely very small)
******* subfamily Newportiinae, Newportia
******** All legs without tarsal spurs; ultimate legs subclavate, tarsus 1 inflated, tarsus 2 small, consisting either of a single small article or absent.
******** Tarsal spurs present on most legs; long tarsus 2 of ultimate legs divided into several (4 – ca 40) variably-distinct secondary articles.

*** 21 Leg Bearing Segments

** Single unpigmented ocellus
*** family Mimopidae
**** genus Mimops

** Four ocelli
*** 21 (23, 39 or 43) Leg Bearing Segments

@endmindmap