@startwbs

+ A
 + B
  + D
   + E
    +_ Scolopendra subcrustalis
    +_ Scolopendra laeta

   + F
    +_ Scolopendra morsitans
   + G
    + H
     +_ Scolopendra spinosissima
     + I
      +_ Scolopendra paradoxa
    + J
     + K 
      + L
       +_ Scolopendra dawydoffi
       +_ Scolopendra multidens
      +_ Akymnopellis chilensis
      +_ Campylostigmus orientalis
      +_ Cormocephalus westwoodi
     + R
      +_ Scolopendra subspinipes
      +_ Scolopendra dehaani 

 + C 
  +_ Arthrorhabdus formosus
  +_ Hemiscolopendra marginata
 +_ Rhysida immarginata
 +_ Ethmostigmus rubripes

@endwbs