@startwbs

*[#b8bb26]:Ordnung
<b>Scolopendromorpha</b>
(Riesenläufer);

**[#fabd2f]:Familie
<b>Cryptopidae</b>;
***[#83a598]:Unterfamilie
<b>Cryptopinae</b>;
***[#83a598]:Unterfamilie
<b>Plutoniuminae</b>;

**[#fabd2f]:Familie 
<b>Mimopidae</b>;

**[#fabd2f]:Familie
<b>Scolopendridae</b>;
***[#83a598]:Unterfamilie
<b>Otostigminae</b>;
****[#a89984]:Stamm
<b>Otostigmini</b>;
****[#a89984]:Stamm
<b>Sterropristini</b>;
***[#83a598]:Unterfamilie
<b>Scolopendrinae</b>;

**[#fabd2f]:Familie 
<b>Scolopocryptopidae</b>;
***[#83a598]:Unterfamilie
<b>Eectonocryptopinae</b>;
***[#83a598]:Unterfamilie
<b>Kethopinae</b>;
***[#83a598]:Unterfamilie
<b>Newportiinae</b>;
***[#83a598]:Unterfamilie
<b>Scolopocryptopinae</b>;

@endwbs