= Scolopendra cingulata

:fn-chilobase: footnote:chilobase[https://chilobase.biologia.unipd.it[2016 - Bonato, Chagas Junior, Edgecombe, Lewis, Minelli, Pereira, Shelley, Stoev, Zapparoli - ChiloBase 2.0 - A World Catalogue of Centipedes (Chilopoda)]]
:fn-2012-kronmüller: footnote:2012-kronmüller[https://www.researchgate.net/publication/259752848_Review_of_the_subspecies_of_Scolopendra_subspinipes_Leach_1815_with_the_new_description_of_the_South_Chinese_member_of_the_genus_Scolopendra_Linnaeus_1758_named_Scolopendra_hainanum_spec_nov_Myriapoda[2012 - Kronmüller - Review of the subspecies of Scolopendra subspinipes Leach, 1815 with the new description of the South Chinese member of the genus Scolopendra Linnaeus, 1758 named Scolopendra hainanum spec. nov.]]
:fn-2017-ahmed: footnote:2017-ahmed[https://www.researchgate.net/publication/312490740_First_record_of_two_Scolopendromorph_centipedes_Scolopendra_subspinipes_Leach_1815_and_Scolopendra_polymorpha_Wood_1861_with_additional_notes_on_Scolopendra_cingulata_Latreille_1829_in_Iraq[2017 - Ahmed - First record of two Scolopendromorph centipedes; Scolopendra subspinipes Leach, (1815) and Scolopendra polymorpha Wood, (1861) with additional notes on Scolopendra cingulata Latreille, (1829) in Iraq]]
:fn-2014-oeyen: footnote:2014-oeyen[https://www.researchgate.net/publication/266085751_The_Evolutionary_History_of_the_Rediscovered_Austrian_Population_of_the_Giant_Centipede_Scolopendra_cingulata_Latreille_1829_Chilopoda_Scolopendromorpha[2014 - Oeyen et al. - The Evolutionary History of the Rediscovered Austrian Population of the Giant Centipede Scolopendra cingulata Latreille 1829 (Chilopoda, Scolopendromorpha)]]
:fn-2016-decker: footnote:2016-decker[https://www.researchgate.net/profile/Hans-Reip/publication/322156351_Rote_Liste_und_Gesamtartenliste_der_Hundertfusser_Myriapoda_Chilopoda_Deutschlands/links/5a48ecef458515f6b0582104/Rote-Liste-und-Gesamtartenliste-der-Hundertfuesser-Myriapoda-Chilopoda-Deutschlands.pdf[2016 - Decker et al. - Rote Liste und Gesamtartenliste der Hundertfüßer (Myriapoda: Chilopoda) Deutschlands, 1. Fassung, Stand Juli 2014]]
:fn-2020-deimezis: footnote:2020-deimezis[https://www.researchgate.net/publication/343135032_A_rare_case_of_saurophagy_by_Scolopendra_cingulata_Chilopoda_Scolopendridae_in_the_central_Aegean_Archipelago_A_role_for_insularity[2020 - Deimezis-Tsikoutas et al. - A rare case of saurophagy by Scolopendra cingulata (Chilopoda: Scolopendridae) in the central Aegean Archipelago: A role for insularity?]]
:fn-2019-cabanillas: footnote:2019-cabanillas[https://www.researchgate.net/publication/333402249_First_observation_of_filial_cannibalism_in_Scolopendra_cingulata_Latreille_1829_Chilopoda_Scolopendromorpha_Scolopendridae[2019 - Cabanillas et al. - First observation of filial cannibalism in Scolopendra cingulata Latreille, 1829 (Chilopoda: Scolopendromorpha: Scolopendridae)]]
:fn-2014-arsovski: footnote:2014-arsovski[https://www.researchgate.net/publication/260478571_Two_fangs_good_a_hundred_legs_better_Juvenile_viper_devoured_by_an_adult_centipede_it_had_ingested[2014 - Arsovski et al. - Two fangs good, a hundred legs better: Juvenile viper devoured by an adult centipede it had ingested]]
:fn-2022-anselmo: footnote:2022-anselmo[https://sisn.pagepress.org/index.php/nhs/article/view/589#:~:text=An%20isolated%20population%20of%20Scolopendra,cingulata%20population.[2022 - Anselmo, Selvaggi - First record of Scolopendra cingulata Latreille 1829 (Chilopoda: Scolopendromorpha: Scolopendridae) in NW Italy and biotope characterization]]
:fn-2020-cabanillas: footnote:2020-cabanillas[https://www.researchgate.net/publication/339687881_First_record_of_Scolopendra_cingulata_Latreille_1829_Chilopoda_Scolopendromorpha_Scolopendridae_in_the_Balearic_Islands_Spain[2020 - Cabanillas et. al. - First record of Scolopendra cingulata Latreille, 1829 (Chilopoda, Scolopendromorpha, Scolopendridae) in the Balearic Islands (Spain)]]

Scolopendra cingulata (Latreille, 1829) ist eine weit verbreitete, vielgestaltige und vergleichsweise gut erforschte Art. Der europäische Riesenläufer, so der deutsche Trivialname dieses Hundertfüßers, findet sich im gesamten Mittelmeer-Raum, darunter dem südlichen Europa, westliche Ausläufern des asiatischen Kontinents und nördlichem Afrika.{fn-chilobase} Die jüngsten Belege stammen aus Österreich (2014){fn-2014-oeyen}, Irak (2017){fn-2017-ahmed}, den Balearen (2020){fn-2020-cabanillas} oder Nordwest-Italien (2022){fn-2022-anselmo}. Lediglich Funde aus Madagaskar, Andaman und den Nicobar Inseln werden aktuell angeweifelt{fn-chilobase}, wie auch Berichte aus Deutschland als eingeschleppte Einzelfälle bewertet werden.{fn-2016-decker}

Bis zur Umbenennung durch Kronmüller gab es auch eine Scolopendra subspinipes-Unterart, die Scolopendra cingulata sehr ähnlich sieht und deswegen früher Scolopendra subspinipes cingulatoides hieß. Seit der Umbenennung ist sie als Scolopendra dawydoffi, benannt nach ihrem Erstbeschreiber, neu klassifiziert.{fn-2012-kronmüller} 

Durch die weite Verbreitung und Vielgestaltigkeit von Skolopendra cingulata, wurde diese Art von vielen Forschern unter unterschiedlichen Namen beschrieben. Mittlerweile wurden jedoch viele Arten mit Scolopendra cingulata synonymisiert und auch alle zuvor beschriebenen Subspezies wurden aufgelöst{fn-chilobase}. Dennoch wird auf Grund der teilweise massiven Größenunterschiede und unterschiedlicher Farbmorphe, je nach Herkunft, schon länger im Hobby diskutiert, ob es sich wirklich um eine einzige Art handelt, oder ob da nicht doch ein Komplex hintersteht.



So wurde unter anderem an Scolopendra cingulata kannibalismus an Jungtieren{fn-2019-cabanillas}, das Erbeuten von Reptilien{fn-2020-deimezis} oder das Befreien aus dem inneren einer Schlange{fn-2014-arsovski} beobachtet. 

TBD: 2010 - Simaiakisa, Giokasb, Korsósc - Morphometric and meristic diversity of the species Scolopendra cingulata Latreille, 1829 (Chilopoda: Scolopendridae) in the Mediterranean region

-- within Africa: Egypt; Libya; Morocco; Tunisia
-- within Asia-Temperate: Cyprus; Tadzhikistan; Turkey
-- within Asia-Tropical: Peninsular Malaysia
-- within Europe: Albania; Austria; Bosnia-Herzegovina; Bulgaria; Croatia; France; Greece; Hungary; Italy; Macedonia; Malta; Moldova; Portugal; Romania; San Marino; Sicilia; Spain; Turkey-in-Europe; Ukraine
Notes: Recorded doubtfully also from Madagascar, Andaman and Nicobar islands.


---
== Attems

Färbung sehr variabel, einfarbig gelbbraun, dunkelbraun, olivgrün bis
tief dunkelgrün („var. hispanica") oder gelbbraun mit breitem dunkelgrünem
Saum am Hinterrand, meist nur zwischen den Längsfurchen, manchmal auch längs des ganzen Hinterrandes. 

Die dunkelgrüne Farbe ist im Alkohol recht unbeständig, so daß die ursprüngliche Farbe älterer Museumsstücke nicht immer feststellbar ist; 

an derselben Lokalität finden sich oft einfarbige und dunkel geränderte Stücke, so daß es vorläufig nicht möglich ist, auf Grund dieser Färbungen Varietäten zu unterscheiden. 

Lange meist etwa 80mm; in Kleinasien bis zu 170mm bei 14mm Breite. 

Kopf punktiert, ohne Furchen.

Antennen 17 bis 22 gliedrig mit 6 kahlen Grundgliedern. 

1. Tergit ohne Furchen; 

Längsfurchen vom 2. oder 3. bis 20. Tergit; 

Berandung vom 5. bis 18. Tergit beginnend, meist vom 7.—12. an. 

Letztes Tergit ohne Medianfurche, hinten flachbogig vorgezogen. 

Kieferfußhüften ohne Furchen, die Zahnplatten so lang wie breit, jede mit 4 oder 5 Zähnen.

2.—20. Sternit mit 2 durchgehenden Längsfurchen, letztes verjüngt, hinten
gestutzt oder etwas gerundet. 

Coxopleurenfortsatz kurz kegelförmig, meist 3 spitzig, selten 1—5 spitzig, auf beiden Beinen manchmal verschieden, z. B. 3+4, 2+3, 5+3, 1+3. 

Endbeine kurz und gedrungen, Präfemur 1,5—2 mal so lang wie breit, dorsal etwas abgeflacht, am Ende mit Gelenkgrube, ventral-lateral meist 2, selten 1 oder 3 oder 4 Dornen; auf beiden Beinen ist die Zahl oft verschieden, z. B. 1+2, 2+3, 2+4, 3+4.

Medial keine Dornen, oben-medial meist 4 Dornen in 2 Reihen, selten 2, 3,
oder 5—8 Dornen; 
auch diese Zahlen oft auf beiden Beinen verschieden, z.B. 2+3, 3+4, 3+5, 3+6, 4+5, 4+6, 4+7. 

Eckdorn meist 4- oder 5spitzig, seltener 2-, 3- oder 6—11 spitzig, auf beiden Beinen oft verschieden; z.B. 1+4, 2+3, 2+4, 2+11, 3+4, 3+5, 4+5, 4+10, 5+6, 5+9, 8+10.


var. obscuripes
Kopf und 1. Tergit sehr dunkel; braun bis, schwarzgrün, die anderen
Tergite braun, Hinterrand zwischen den Längsfurchen oder darüber hinaus
spangrün.

Antennen und Endbeine rotgelb.

20 Beinpaar mit 1 Tarsalsporn.
Coxopleuralfortsatz meist mit 3, selten 1 oder 2 Spitzen. 

Bedornung der Endbeine variabel wie bei der Stammform, ventral-lateral meist 2, oben-medial meist 4, Eckdorn meist mit 5 Dornen.